theme: jekyll-theme-architect
title: [The Looter's WeatherApp]
description: [A short description of your site's purpose]
author :
  name : Skip McGee
  email : davidfranklinmcgee@gmail.com
  github : skipmcgee
  
  
